# Generated by Django 5.0.6 on 2026-01-21 21:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('type', models.CharField(choices=[('assignment_due', 'Assignment Due'), ('exam', 'Exam'), ('meeting', 'Meeting'), ('break', 'Break'), ('other', 'Other')], max_length=32)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('teacher', 'Teacher'), ('coordinator', 'Coordinator'), ('guardian', 'Guardian')], default='teacher', max_length=16)),
                ('source_type', models.CharField(blank=True, default='', max_length=32)),
                ('source_id', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(default='published', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='classrooms.classroom')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_calendar_events', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start'],
                'indexes': [models.Index(fields=['classroom', 'start'], name='school_cale_classro_3acd71_idx'), models.Index(fields=['type'], name='school_cale_type_7a8ca5_idx'), models.Index(fields=['source_type', 'source_id'], name='school_cale_source__643218_idx')],
            },
        ),
    ]
