# Generated by Django 6.0.1 on 2026-01-19 07:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField()),
                ('name', models.CharField(max_length=100)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_categories', to='classrooms.classroom')),
            ],
            options={
                'verbose_name_plural': 'Grade Categories',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='GradeItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('max_score', models.DecimalField(decimal_places=2, help_text='Maximum possible score for this item', max_digits=5)),
                ('graded_at', models.DateField(help_text='Date the assessment took place or is due')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='grades.gradecategory')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_items', to='classrooms.classroom')),
            ],
            options={
                'ordering': ['graded_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='GradeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('graded_at', models.DateTimeField(auto_now=True)),
                ('graded_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades_given', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_entries', to='students.student')),
                ('grade_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='grades.gradeitem')),
            ],
            options={
                'verbose_name_plural': 'Grade Entries',
                'indexes': [models.Index(fields=['grade_item', 'student'], name='grades_grad_grade_i_227488_idx')],
                'unique_together': {('grade_item', 'student')},
            },
        ),
    ]
