# Generated by Django 6.0.1 on 2026-01-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='animal_id',
            field=models.CharField(blank=True, default='🦁', max_length=10),
        ),
    ]
